FROM java:8-jdk-alpine
COPY ./target/ConsumerAPI-1.0-SNAPSHOT.jar /usr/app/
COPY ./config.yml /usr/app/
WORKDIR /usr/app
EXPOSE 9181
ENTRYPOINT ["java", "-cp", "ConsumerAPI-1.0-SNAPSHOT.jar","com.daitan.pocmiddleware.ConsumerAPIApplication", "server", "config.yml"]